### ISSUE TITLE
Lost title color after HA update

### ISSUE THREAD

**Issue by Vourhey** [PinoutLTD/HA.Themes#2]
Hello!

After updating HA Green to the latest version, the color in the title is missing

<img width="259" alt="Screenshot 2024-12-09 at 11 31 56 AM" src="https://github.com/user-attachments/assets/bce5f91d-ba2e-46d9-acbe-6e953e944e0c">

```
Core 2024.12.1
Supervisor 2024.11.4
Operating System 14.0
Frontend 20241127.6
```

Expected title:

<img width="260" alt="Screenshot 2024-12-09 at 11 32 05 AM" src="https://github.com/user-attachments/assets/f24855db-16a3-46c5-80e3-da3c7fa64800">

```
Core 2024.9.1
Frontend 20240906.0
```

Can you please check this? Thank you

**Comment by zirreal** [comment]
Updated the colors in the theme. Should be working now.

**Comment by Vourhey** [comment]
Yes, thank you 👍
